// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsndsbqbqvbjwyqjqaav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbmRzYnFicXZiand5cWpxYWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5ODc3NTAsImV4cCI6MjA3ODU2Mzc1MH0.HGcot0l7dVXbv9uIhZrQlV-Lrg7H4ydckMDKG6cH0P0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});